
language: node_js
node_js:
  - 8

# command to install dependencies
install: "npm install"

cache:
  directories:
    - "node_modules"

# scripts run as part of build
scripts:
  - npm install -g serverless
  # - npm run lint
  # - npm test

after_success:
  # - nyc report --reporter=json > coverage/coverage.json
  - sls deploy || exit 1